source 'https://rubygems.org'

gem 'activesupport', '~>7.0.4'
gem 'fluent-plugin-concat', '~>2.5.0'
gem 'fluent-plugin-detect-exceptions', '~>0.0.15'
gem 'fluent-plugin-elasticsearch', '~>5.3.0'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>3.1.3'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-prometheus', '~>2.0.3'
gem 'fluent-plugin-systemd', '~>1.0.5'
gem 'fluent-plugin-rewrite-tag-filter', '~>2.4.0'
gem 'fluent-plugin-kafka', '~>0.18.1'
gem 'extlz4', '~>0.3.3'
gem 'zstd-ruby', '~>1.5.5'
gem 'snappy', '~>0.3.0'
